### PR TITLE
docs: add provider configuration documentation for env variables

### PR DESCRIPTION
**Pull request by oliviermichaelis**
Hi @BeryJu, thanks for everything you've done so far!
While configuring the provider, I had to look into the code to check if I could pass environment variables to it. This PR intends to add some documentation, as well as facilitate the generation of the documentation.

* Add documentation for configuring provider with environment variables
* By introducing `tools/tools.go`, we manage the dependency on `terraform-plugins-docs` in the `go.mod`. By that, we can make sure that we don't end up in a situation where two contributers have different versions of `terraform-plugins-docs` and therefore generate different documentation
* I ran `go mod tidy` and removed two (unneeded?) dependencies
* Running `go generate` will lead to slightly different formatting of the files in `docs`. I didn't include them in the PR, as I don't want to spam the PR with 50+ formatting changes.

I'm looking forward to your thoughts on this :)

### CODE REVIEW

**Comment by BeryJu** [comment]
Cheers for the PR, the formatting differences are from the fact that `github.com/hashicorp/terraform-plugin-docs/cmd/tfplugindocs` does not support the `subcategory` attribute, which I added by hand.

Also `Authentik` is supposed to be lowercase on purpose :P 

Also also, the depencies that were removed might be part of the testing tools, CI should tell.

**Comment by oliviermichaelis** [comment]
> github.com/hashicorp/terraform-plugin-docs/cmd/tfplugindocs does not support the subcategory attribute, which I added by hand

What about creating a template in `templates/` for each resource? I've commited an example for `flow.md`, which preserves the subcategory :) I'm aware that it would be a lot of work to create 50+ templates, but I think it might be easier to maintain in the long-term.


> Also Authentik is supposed to be lowercase on purpose :P

I wasn't aware of that, I've changed everything to lowercase now :)

**Comment by BeryJu** [comment]
> > github.com/hashicorp/terraform-plugin-docs/cmd/tfplugindocs does not support the subcategory attribute, which I added by hand
> 
> What about creating a template in `templates/` for each resource? I've commited an example for `flow.md`, which preserves the subcategory :) I'm aware that it would be a lot of work to create 50+ templates, but I think it might be easier to maintain in the long-term.
>

Good idea, that might be the only way to keep the categories without manually merging changes in those files. I'm still hoping that the plugindocs command will eventually add subcategory support, but for now this is probably the only way.

**Comment by oliviermichaelis** [comment]
I went ahead and added the templates for all resources! :)
* every file in `docs` has a corresponding template in `templates`
* added a note in the README on how to regenerate the documentation with `go generate`

**Comment by oliviermichaelis** [comment]
Thanks for everything @BeryJu! :tada:

**Pull request merged**
